server:
  port: 8888
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:myBatis-config.xml

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/crm_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: zfx15255325432
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springfox:
  documentation:
    enable: true
#访问地址:http://localhost:8080/swagger-ui/index.heml
swagger:
  base-package: com.zengfanfan.crm.controller
  authorization:
    name: zeng
    title: 文档
    version: crm项目
